In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [7]:
a=np.array([1,2,3,4,5])
a.ndim

1

In [4]:
aa=np.array([[1,2,3,4],[5,6,7,8]])
aa

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
aa=np.array([[1,2,3,4],[5,6,7,8]])
aa.ndim

2

In [50]:
s=np.array([[[1,2,3],[3,5,6]],[[5,6,7],[8,9,4]]])
s

array([[[1, 2, 3],
        [3, 5, 6]],

       [[5, 6, 7],
        [8, 9, 4]]])

In [51]:
s=np.array([[[1,2,3],[3,5,6],[5,6,7],[8,9,4]]])
s

array([[[1, 2, 3],
        [3, 5, 6],
        [5, 6, 7],
        [8, 9, 4]]])

In [9]:
s=np.array([[[1,2,3],[3,5,6]],[[5,6,7],[8,9,4]]])
s.ndim

3

In [6]:
a=np.array([[[1,2,3,4],[5,7,8,9]]])
a

array([[[1, 2, 3, 4],
        [5, 7, 8, 9]]])

In [10]:
a=np.array([[[1,2,3,4],[5,7,8,9]]])
a.ndim

3

In [12]:
a=np.array(0)
b=np.array([1,2,3,4,5])
aa=np.array([[1,2,3,4],[5,6,7,8]])
s=np.array([[[1,2,3],[3,5,6]],[[5,6,7],[8,9,4]]])
print(a.ndim)
print(b.ndim)
print(aa.ndim)
print(s.ndim)

0
1
2
3


In [14]:
aa=np.array([[1,2,3,4],[5,6,7,8]])
print(aa)
aa.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [15]:
aa=np.array([[1,2,3,4],[5,6,7,8]])
print(aa)
aa.size

[[1 2 3 4]
 [5 6 7 8]]


8

In [20]:
aa=np.array([[1,2,3,4],[5,6,7,8]])
print(aa)


[[1 2 3 4]
 [5 6 7 8]]


In [23]:
aa=np.array([1,2,3,4,5,6],ndmin=3)
aa

array([[[1, 2, 3, 4, 5, 6]]])

In [22]:
aa=np.array([1,2,3,4,5,6],ndmin=3)
aa.ndim

3

In [25]:
aa=np.array([1,2,3,4,5,6],ndmin=5)
aa

array([[[[[1, 2, 3, 4, 5, 6]]]]])

In [39]:
aa=np.array([1,2,3,4,5,6],ndmin=5)
aa.ndim
aa

array([[[[[1, 2, 3, 4, 5, 6]]]]])

In [28]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])
x=np.copy(arr)
x[2]=500
print(arr)
print(x)

[ 10  20  30  40  50  60  70  80  90 100]
[ 10  20 500  40  50  60  70  80  90 100]


In [29]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])
x=arr.view()
x[2]=500
print(arr)
print(x)

[ 10  20 500  40  50  60  70  80  90 100]
[ 10  20 500  40  50  60  70  80  90 100]


In [30]:
arr=np.array([10,20,30,40,50,60,70,80,90,100,110,120])
r=arr.reshape(4,3)
r

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [32]:
arr=np.array([10,20,30,40,50,60,70,80,90,100,110,120])
r=arr.reshape(2,6)
r

array([[ 10,  20,  30,  40,  50,  60],
       [ 70,  80,  90, 100, 110, 120]])

In [33]:
ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
a=ar.reshape(2,3,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [48]:
ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
a=ar.reshape(3,3,2)
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [36]:
aa=np.array([[1,2,3,4],[5,6,7,8]])
aa

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
aa=np.array([[1,2,3,4],[5,6,7,8]],ndmin=3)
a=aa.reshape(-1)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [2]:
import numpy as np
arr=np.array([10,20,30,40,50,60,70,80,90,100,110,120])
arr[4]

np.int64(50)

In [3]:
import numpy as np
arr=np.array([10,20,30,40,50,60,70,80,90,100,110,120])
arr[7]

np.int64(80)

In [4]:
import numpy as np
arr=np.array([10,20,30,40,50,60,70,80,90,100,110,120])
arr[-5]

np.int64(80)

In [5]:
import numpy as np
arr=np.array([10,20,30,40,50,60,70,80,90,100,110,120])
arr[2:7]

array([30, 40, 50, 60, 70])

In [9]:
arr[:-3]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
arr[-3:]

array([100, 110, 120])

In [12]:
arr[-4:-1]

array([ 90, 100, 110])

In [13]:
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [15]:
a=np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
a=np.zeros((2,3,5))
a

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [18]:
arr=np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [20]:
a=np.ones((6,6))
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
a=np.ones((3,4,6))
a

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [22]:
a=np.ones((3,4,6),dtype='int')
a

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])

In [23]:
a=np.ones((3,4,6),dtype='int')
print(a)

[[[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]]


In [24]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [25]:
arr=np.arange(5,20)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [26]:
arr=np.arange(2,20,3)
arr

array([ 2,  5,  8, 11, 14, 17])

In [28]:
a=np.linspace(2,15,4)
a

array([ 2.        ,  6.33333333, 10.66666667, 15.        ])

In [30]:
a=np.linspace(10,50,10)
a

array([10.        , 14.44444444, 18.88888889, 23.33333333, 27.77777778,
       32.22222222, 36.66666667, 41.11111111, 45.55555556, 50.        ])

In [31]:
a=np.linspace(10,50,10,dtype='int')
a

array([10, 14, 18, 23, 27, 32, 36, 41, 45, 50])

In [33]:
ar=np.array([1,2,3,4])
arr=np.array([6,7,8,4])
print(ar+arr)
print(ar-arr)
print(ar*arr)
print(ar/arr)

[ 7  9 11  8]
[-5 -5 -5  0]
[ 6 14 24 16]
[0.16666667 0.28571429 0.375      1.        ]


In [36]:
ar=np.array([[1,2,3,4],[5,6,7,8]])
a=np.array([[4,3,1,2],[7,4,2,8]])
print(ar+a)

[[ 5  5  4  6]
 [12 10  9 16]]


In [41]:
arr=np.arange(25)
a=arr.reshape(5,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [42]:
a=np.array([1,2,3,4,5])
np.sum(a)

np.int64(15)

In [3]:
import numpy as np

In [4]:
a=np.array([[ 5 , 5 , 4 , 6],
[12, 10 , 9 , 16]])

np.sum(a)

np.int64(67)

In [43]:
a=np.array([1,2,3,4,5])
aa=np.sum(a)
aa

np.int64(15)

In [45]:
ar=np.array([1,2,3,4])
arr=np.array([6,7,8,4])
x=np.concatenate((ar,arr))
x

array([1, 2, 3, 4, 6, 7, 8, 4])

In [ ]:
ar=np.array([[1,2,3,4],[5,6,7,8]])
a=np.array([[4,3,1,2],[7,4,2,8]])
x=np.concatenate((ar,a),axis=1)
x

array([[1, 2, 3, 4, 4, 3, 1, 2],
       [5, 6, 7, 8, 7, 4, 2, 8]])

In [49]:
ar=np.array([[1,2,3,4],[5,6,7,8]])
a=np.array([[4,3,1,2],[7,4,2,8]])
x=np.concatenate((ar,a),axis=0)
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 3, 1, 2],
       [7, 4, 2, 8]])

In [2]:
import numpy as np

In [3]:
ar=np.array([[[1,2,3,4],[5,6,7,8],[5,4,3,1]]])
a=np.array([[[4,3,1,2],[7,4,2,8],[0,6,8,2]]])
x=np.concatenate((ar,a),axis=1)
x

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [5, 4, 3, 1],
        [4, 3, 1, 2],
        [7, 4, 2, 8],
        [0, 6, 8, 2]]])

In [5]:
arr=np.array([10,20,30,40,50,60,70,80,90,100,110,120])
a=np.array_split(arr,8)
a

[array([10, 20]),
 array([30, 40]),
 array([50, 60]),
 array([70, 80]),
 array([90]),
 array([100]),
 array([110]),
 array([120])]

In [6]:
arr=np.array([10,20,30,40,50,60,70,80,90,100,110,120])
a=np.array_split(arr,15)
a

[array([10]),
 array([20]),
 array([30]),
 array([40]),
 array([50]),
 array([60]),
 array([70]),
 array([80]),
 array([90]),
 array([100]),
 array([110]),
 array([120]),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64)]

In [7]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
ar=np.hsplit(a,2)
ar

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [8]:
a=np.array([1,5,2,3,4,5,6,7,5,8,9,10])
ar=np.where(a==5)
ar

(array([1, 5, 8]),)

In [3]:
import numpy as np
a=np.array([1,2,3,4],dtype='S')
print(a)
print(a.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [4]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([9,0,1,2])
aa=np.stack((a,b,c))
aa

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [5]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([9,0,1,2])
aa=np.stack((b,a,c))
aa

array([[5, 6, 7, 8],
       [1, 2, 3, 4],
       [9, 0, 1, 2]])

In [6]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([9,0,1,2])
aa=np.vstack((a,b,c))
aa

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [8]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([9,0,1,2])
aa=np.hstack((a,b,c))
aa

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2])

In [10]:
a=np.array([[1,2,3,4,5,6,7,8,9],[5,6,7,8,3,5,9,7,2]])
ar=np.hsplit(a,3)
ar
                

[array([[1, 2, 3],
        [5, 6, 7]]),
 array([[4, 5, 6],
        [8, 3, 5]]),
 array([[7, 8, 9],
        [9, 7, 2]])]

In [12]:
a=np.array([[1,2,5,4,5,6,7,8,9],[5,6,7,8,8,5,9,7,2]])
np.where(a==5)

(array([0, 0, 1, 1]), array([2, 4, 0, 5]))

In [3]:
import numpy as np

In [5]:
ar=np.array([1,2,3,4,5,6,7,8,9,10])
a=np.where(ar%2==0)
print(ar[a])

[ 2  4  6  8 10]


In [13]:
ar=np.array([1,2,3,4,6,7,8,9,10])
a=np.searchsorted(ar,5)
a

np.int64(4)

In [14]:
ar=np.array([1,2,3,4,6,7,8,9,10])
a=np.searchsorted(ar,11)
a

np.int64(9)

In [15]:
ar=np.array([1,2,3,4,6,7,8,9,10])
a=np.searchsorted(ar,15)
a

np.int64(9)

In [17]:
ar=np.array([1,2,3,4,6,7,9,10])
a=np.searchsorted(ar,(5,8))
a

array([4, 6])

In [18]:
ar=np.array([1,2,3,4,6,7,9,10])
a=np.searchsorted(ar,(5,8,11))
a

array([4, 6, 8])

In [19]:
ar=np.array([1,2,3,4,5,6,7,8,9,10])
arr=np.insert(ar,3,50)
arr

array([ 1,  2,  3, 50,  4,  5,  6,  7,  8,  9, 10])

In [20]:
a=np.array([7,8,4,9,3,2,5,0])
aa=np.sort(a)
aa

array([0, 2, 3, 4, 5, 7, 8, 9])

In [24]:
a=np.array(["a","f","r","g","d","i","e"])
np.sort(a)

array(['a', 'd', 'e', 'f', 'g', 'i', 'r'], dtype='<U1')

In [25]:
a=np.array([1,2,3,4,5])
a.max()

np.int64(5)

In [26]:
a=np.array([1,2,3,4,5])
a.min()

np.int64(1)

In [6]:
a=np.array([1,2,3,4,5,6])
a.mean()

np.float64(3.5)

In [29]:
a=np.array([1,2,3,4,5])
np.median(a)

np.float64(3.0)

In [30]:
a=np.array([1,2,3,4,5,3,2,4,6])
aa=np.unique(a)
aa

array([1, 2, 3, 4, 5, 6])

In [31]:
a=np.array([1,2,3,4,5])
np.flip(a)

array([5, 4, 3, 2, 1])

In [34]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
np.flip(arr,axis=1)

array([[4, 3, 2, 1],
       [8, 7, 6, 5]])

In [33]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
np.flip(arr,axis=0)

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [36]:
a=np.array([10,20,30])
np.save('my.npy',a)

In [37]:
np.load('my.npy')

array([10, 20, 30])

In [39]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

tasks

In [55]:
ar=np.array([1,2,3,4,5,6,7,8,9,10])
a=np.where(ar%2==0)
print(ar[a])
print("indexs of even numbers are = ",a)

[ 2  4  6  8 10]
indexs of even numbers are =  (array([1, 3, 5, 7, 9]),)


In [56]:
ar=np.array([1,2,3,4,5,6,7,8,9,10])
ar[np.where(ar%2==0)]

array([ 2,  4,  6,  8, 10])

In [58]:
ar=np.array([1,2,3,4,5,6,7,8,9,10])
ar[np.where(ar%2!=0)]

#print("indexs of odd numbers are = ",a)

array([1, 3, 5, 7, 9])

In [59]:
ar=np.array([1,2,3,4,5,6,7,8,9])
a=np.searchsorted(ar,10)
np.insert(ar,a,80)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 80])

In [98]:
ar=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
s=np.sum(ar,axis=1)
print(ar)
s
    



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([ 6, 15, 24, 33])

In [85]:
a=np.array([1,2,3,4])
for i in a:
    print(i)
# print(a[0])
# print(a[1])
# print(a[2])
# print(a[3])


1
2
3
4


In [88]:
a=np.array([[1,2,3],[4,5,6]])
for i in a:
    for j in i:
        print(j)

1
2
3
4
5
6


In [77]:
a=np.array([1,5,3,4])
i=np.searchsorted(a,5)
t=np.insert(a,i,5)
print(t)


[1 5 3 4 5]


a=np.array([1,5,3,4])

In [101]:
a=np.array([1,5,3,4])
a[::-1]
t=np.sort(a)
t
t[::-1]

array([5, 4, 3, 1])

In [13]:
a=np.array([1,5,3,4])
#a[::-1]
t=np.sort(a)
t
t[::-1]

array([5, 4, 3, 1])

In [15]:
a=np.array([[1,2,3,4],[7,8,9,0]])
b=np.array([5,6,7,8])
print(a+b)

[[ 6  8 10 12]
 [12 14 16  8]]


In [16]:
arr=np.array([1,2,3,4,5,np.nan,8])
arr

array([ 1.,  2.,  3.,  4.,  5., nan,  8.])

In [17]:
arr=np.array([1,2,3,4,5,np.nan,8])
r=np.isnan(arr)
r

array([False, False, False, False, False,  True, False])

In [18]:
arr=np.array([1,2,3,4,5,np.nan,8])
r=np.isnan(arr).astype(int)
r

array([0, 0, 0, 0, 0, 1, 0])

In [19]:
arr=np.array([1,2,3,4,5,np.nan,8,7,3,np.nan])
print(sum(np.isnan(arr)))

2


In [21]:
arr=np.array([1,2,3,4,5,np.nan,8,7,3,np.nan])
arr[np.isnan(arr)]=50
arr

array([ 1.,  2.,  3.,  4.,  5., 50.,  8.,  7.,  3., 50.])

In [22]:
arr=np.array([1,2,3,4,5,np.nan,8,7,3,np.nan])
arr[np.isnan(arr)]=[50,7]
arr

array([ 1.,  2.,  3.,  4.,  5., 50.,  8.,  7.,  3.,  7.])

In [23]:
arr=np.array([1,2,3,4,5,np.nan,8,7,3,np.nan])
cl=arr[~np.isnan(arr)]
cl

array([1., 2., 3., 4., 5., 8., 7., 3.])

In [24]:
a=np.array([1,np.nan,3])
b=np.array([2, 3, np.nan])
print(a+b)

[ 3. nan nan]


In [25]:
arr=np.array([1,2,3,4,5])
y=arr*5
y

array([ 5, 10, 15, 20, 25])

In [26]:
arr=np.array([1,2,3,4,5])
y=arr+5
y

array([ 6,  7,  8,  9, 10])

In [40]:
import random
a=random.randint(5,20)
a

13

In [43]:
a=np.random.randint(5,20,size=(4,3))
a

array([[17,  8,  5],
       [15, 10, 19],
       [13, 19, 19],
       [10, 19, 19]], dtype=int32)

In [44]:
a=np.random.randint(5,20,size=(2,4,3))
a

array([[[ 8, 15, 19],
        [10,  9, 19],
        [16,  5,  5],
        [ 9, 18, 17]],

       [[10,  7, 19],
        [ 7, 12,  7],
        [ 8,  6, 16],
        [16, 19, 15]]], dtype=int32)

In [58]:
from numpy import random
a=random.rand(5)
a

array([0.86512003, 0.22403984, 0.51602911, 0.4547329 , 0.24921873])

In [62]:
a=np.random.randint(50)
a

3

In [ ]:
#____________________________________________ASSIGNMENT2______________________________________________

In [66]:
a=np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [2]:
import numpy as np

In [5]:
a=np.arange(21)
a
b=a[::2]
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
a=np.random.randint(1,10,size=(3,3))
print(a)
b=a.shape
c=a.size
print(b)
print(c)
d=a.dtype
print(d)

[[7 4 1]
 [4 5 3]
 [7 2 3]]
(3, 3)
9
int32


In [74]:
a=np.array([2,4,6,8])
b=np.array([1,3,5,7])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 3  7 11 15]
[1 1 1 1]
[ 2 12 30 56]
[2.         1.33333333 1.2        1.14285714]


In [7]:
a=np.zeros(10)
b=np.insert(a,5,1)
print(b)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [25]:
a=np.random.randint(35,50,size=(3,3))
print(a)
b=a.max()
print("max = ",b)
c=a.min()
print("min = ",c)
d=a.sum()
print("sum = ",d)


[[42 47 38]
 [45 48 36]
 [42 42 39]]
max =  48
min =  36
sum =  379


In [83]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=a.reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
a=np.random.randint(1,50,size=(3,3))
print(a)


print("\n","first row = ",a[0])
#b=np.a[2],axis=1
#b
#print("\n","last colomn = ",b)
c=a[1,2]
print(c)



[[24 13 30]
 [44 39 24]
 [ 7 45 46]]

 first row =  [24 13 30]
24


In [42]:
a=np.random.randint(1,10,size=(2,3,3))
print(a)

[[[2 3 7]
  [3 6 7]
  [3 9 8]]

 [[3 6 8]
  [8 2 6]
  [9 1 9]]]


In [45]:
a=np.arange(1,10)
print(a)
for i in a:
    if i>5:
        print(i)

[1 2 3 4 5 6 7 8 9]
6
7
8
9


In [2]:
import numpy as np

In [20]:
a=np.random.randint(1,10,size=(3,3))
b=np.random.randint(1,10,size=(3,3))
print("a=",a)
print("\n","b=",b)

print("\n","matrix addition = ", "\n",a+b)
print("matrix subtraction = ","\n",a-b)
print("matrix dot product = ","\n",a*b)

a= [[2 2 6]
 [6 2 4]
 [9 4 1]]

 b= [[9 3 7]
 [1 1 9]
 [6 3 5]]

 matrix addition =  
 [[11  5 13]
 [ 7  3 13]
 [15  7  6]]
matrix subtraction =  
 [[-7 -1 -1]
 [ 5  1 -5]
 [ 3  1 -4]]
matrix dot product =  
 [[18  6 42]
 [ 6  2 36]
 [54 12  5]]


In [23]:
a=np.array([10,20,30,40,50],dtype="float")
print(a)
a=np.array([10,20,30,40,50],dtype="int")
print(a)

[10. 20. 30. 40. 50.]
[10 20 30 40 50]


In [27]:
a=np.random.randint(1,10,size=(4,4))
print(a)

[[2 5 3 6]
 [6 8 5 6]
 [1 4 4 1]
 [9 2 4 7]]
